#!/usr/bin/php
<?php

if (php_sapi_name() !== 'cli') {
    exit;
}

require __DIR__ . '/vendor/autoload.php';

use App\JourneySteps;

$js = new JourneySteps();
$js->readJourneySteps('./data/journeysteps.json');
$orderedJourney = $js->orderJourneySteps();
print_r($orderedJourney);