#!/usr/bin/php
<?php

if (php_sapi_name() !== 'cli') {
    exit;
}

require __DIR__ . '/vendor/autoload.php';

use App\JourneySteps;

$js = new JourneySteps();

print_r($js->readJourneySteps('./data/journeysteps.json'));